# Generated by Django 2.2 on 2020-10-06 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('phone', models.IntegerField(blank=True, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='Город')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='Отделение')),
                ('waybill', models.IntegerField(blank=True, verbose_name='ТТН')),
                ('order', models.TextField(blank=True, max_length=250, verbose_name='Заказ')),
                ('comment', models.TextField(blank=True, max_length=250, verbose_name='Комментарий')),
                ('state', models.IntegerField(choices=[(1, 'Новый'), (2, 'Переговоры'), (3, 'Ожидается оплата'), (4, 'В производстве'), (5, 'Ожидает отгрузку'), (6, 'В пути'), (7, 'В отделении'), (8, 'Оплачен'), (9, 'Отказ на почте'), (10, 'Отмена'), (11, 'Возврат/Обмен')], verbose_name='Статус')),
                ('price', models.IntegerField(blank=True, verbose_name='Сумма')),
                ('create_date', models.DateTimeField(blank=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(blank=True, verbose_name='Дата изменения')),
                ('pay_date', models.DateTimeField(blank=True, verbose_name='Дата оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
