# Generated by Django 2.2 on 2020-10-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='waybill',
            field=models.IntegerField(blank=True, unique=True, verbose_name='ТТН'),
        ),
    ]
