# Generated by Django 2.2 on 2020-10-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201007_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='waybill',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ТТН'),
        ),
    ]
