# Generated by Django 2.2 on 2020-10-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='turbosms_api',
            field=models.CharField(blank=True, max_length=150, verbose_name='API ключ TurboSMS'),
        ),
        migrations.AddField(
            model_name='project',
            name='turbosms_sender',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подпись TurboSMS'),
        ),
        migrations.AlterField(
            model_name='project',
            name='np_api',
            field=models.CharField(blank=True, max_length=150, verbose_name='API ключ Новая Почта'),
        ),
    ]
