# Generated by Django 2.2 on 2020-12-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message_1',
            field=models.CharField(default='-', max_length=150, verbose_name='Сообщение №1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message_2',
            field=models.CharField(default='-', max_length=150, verbose_name='Сообщение №2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message_3',
            field=models.CharField(default='-', max_length=150, verbose_name='Сообщение №3'),
        ),
    ]
