# Generated by Django 2.2 on 2020-12-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20201227_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_send_messages',
            field=models.BooleanField(default=False, verbose_name='Не отправлять СМС'),
        ),
    ]
