# Generated by Django 2.2 on 2020-12-25 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_transaction_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purpose',
            options={'verbose_name': 'Назначение', 'verbose_name_plural': 'Назначения'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.Purpose', verbose_name='Назначение'),
        ),
    ]
