# Generated by Django 2.2 on 2021-01-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primaryproduct',
            options={'verbose_name': 'Сырье', 'verbose_name_plural': 'Сырье'},
        ),
        migrations.AlterModelOptions(
            name='primaryproducttype',
            options={'verbose_name': 'Тип сырья', 'verbose_name_plural': 'Типы сырья'},
        ),
        migrations.AlterField(
            model_name='primaryproductsupplier',
            name='comment',
            field=models.CharField(blank=True, max_length=150, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='primaryproductsupplier',
            name='link',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='primaryproductsupplier',
            name='phone',
            field=models.CharField(blank=True, max_length=150, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(default=0, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, verbose_name='Акционная стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.ProductSize', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.IntegerField(blank=True, verbose_name='Оптовая стоимость'),
        ),
    ]
