# Generated by Django 2.2 on 2021-01-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210125_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryproduct',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Акционная стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_price',
            field=models.IntegerField(default=0, verbose_name='Стандартная стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Оптовая стоимость'),
        ),
    ]
